/* Proxytunnel - (C) 2001 Jos Visser / Mark Janssen    */
/* Contact:             josv@osp.nl / maniac@maniac.nl */

/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

/* cmdline.h */
/* File autogenerated by gengetopt version 2.4 - Modified by Maniac */

#ifndef _cmdline_h
#define _cmdline_h

struct gengetopt_args_info {
  char * user_arg;	/* Username to send to HTTPS proxy for authentication.  */
  char * pass_arg;	/* Password to send to HTTPS proxy for authentication.  */
  char * proxyhost_arg;	/* HTTPS Proxy host to connect to.  */
  int proxyport_arg;	/* HTTPS Proxy host portnumber to connect to.  */
  char * desthost_arg;	/* Destination host to built the tunnel to.  */
  int destport_arg;	/* Destination host portnumber to built the tunnel to.  */
  int verbose_flag;	/* Turn on verbosity (default=off).  */
  int inetd_flag;	/* Turn on inetd (default=off).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int user_given ;	/* Whether user was given.  */
  int pass_given ;	/* Whether pass was given.  */
  int proxyhost_given ;	/* Whether proxyhost was given.  */
  int proxyport_given ;	/* Whether proxyport was given.  */
  int desthost_given ;	/* Whether desthost was given.  */
  int destport_given ;	/* Whether destport was given.  */
  int verbose_given ;	/* Whether verbose was given.  */
  int inetd_given ;	/* Whether inetd was given.  */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#endif /* _cmdline_h */
