name: Build for Windows (Cygwin)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: cygwin/cygwin-install-action@v6.1
    - name: test
      run: bash "ls /usr/include"
    - name: test2
      run: bash "ls /usr/include/netinet"
    - name: Build
      run: bash "make && make docs"
