name: Build for Windows (Cygwin)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: cygwin/cygwin-install-action@v6.1
      with:
        packages: cygwin-devel
    - name: test
      shell: bash {0}
      run: ls /usr/include
    - name: test2
      shell: bash {0}
      run: ls /usr/include/netinet
    - name: Build
      shell: bash {0}
      run: make && make docs
